version: '2'
volumes:
  fs_database:
services:
  app:
    image: 'ruvents/php:7.4'
    links:
      - database
    environment:
      DOCKER: yep
    env_file: .env
    volumes:
      - '.:/var/www/html/'
      - './docker/bootstrap.sh:/init.sh'
  nginx:
    image: nginx
    links:
      - app
    volumes:
      - './docker/nginx.${ENVIRONMENT}.conf:/etc/nginx/nginx.conf'
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    volumes_from:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  database:
    image: 'postgres:12.3'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - './docker/database.sql:/docker-entrypoint-initdb.d/dump.sql'
      - 'fs_database:/var/lib/postgresql/data'
