version: '2'
volumes:
  fs_database:
services:
  app:
    image: 'ruvents/php:7.4'
    links:
      - database
    environment:
      DOCKER: yep
    env_file: .env
    volumes:
      - '.:/var/www/html/'
      - './docker/bootstrap.sh:/init.sh'
  nginx:
    image: nginx
    ports:
      - '80:80'
    links:
      - app
    volumes:
      - './docker/nginx.conf:/etc/nginx/nginx.conf'
    volumes_from:
      - app
  database:
    image: 'postgres:12.3'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - './docker/database.sql:/docker-entrypoint-initdb.d/dump.sql'
      - 'fs_database:/var/lib/postgresql/data'